
---
  - name: Copy files
    become: true
    copy:
      src: /root/project/artifact.tar.gz
      dest: /home/ubuntu
  # - name: Unarchive
  #   become: true
  #   shell : |
  #       cd /home/ubuntu/
  #       tar xvzf artifact.tar.gz -C .
  - name: "Install package dependencies"
    shell: |
      cd ~/home/ubuntu
      tar -xzvf backend_artifact.tar.gz -C backend
      rm backend_artifact.tar.gz
      cd backend/
      npm run build
      cd dist
      pm2 start npm --name backend -- start